language: php

sudo: false

php:
  - '7.2'
  - '7.3'
  - 7.4snapshot

env:
  - DEPENDENCIES=""
  - DEPENDENCIES="--classmap-authoritative"

matrix:
  allow_failures:
    - php: 7.4snapshot

before_script:
  - composer self-update
  - composer update --prefer-dist $DEPENDENCIES

script:
  - ./vendor/bin/phpcs
  - ./vendor/bin/phpunit
